name: Discord-Clone Tests

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
 workflow_dispatch:

jobs:
 test:
   runs-on: ubuntu-latest

   steps:
     # Checkout the repository
     - name: Checkout code
       uses: actions/checkout@v3

     # Set up .NET
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '9.0.x'

     # Restore dependencies
     - name: Restore dependencies
       run: dotnet restore ./Discord-Clone.Server

     # Build the application
     - name: Build application
       run: dotnet build ./Discord-Clone.Server --configuration Release --no-restore

     # Run tests and output results in TRX format
     - name: Run tests
       run: dotnet test ./Discord-Clone.Server.Tests/Discord-Clone.Server.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

     # Upload test results
     - name: Upload test results
       uses: actions/upload-artifact@v3
       with:
         name: test-results
         path: ./Discord-Clone.Server.Tests/TestResults/